"""Update Table CV

Revision ID: d5cdd36e3403
Revises: 
Create Date: 2026-05-18 20:34:34.626589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5cdd36e3403'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('articles')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=200), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('categories', sa.VARCHAR(length=100), nullable=True),
    sa.Column('date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    # ### end Alembic commands ###
